"use client";

import PublicSafetyPageShell, { type PublicSafetyReport } from "./PublicSafetyPageShell";

const sources = [
  "Jobs and Skills Australia (JSA), Connecting for Impact - The Jobs and Skills Report 2025, JSA, 2025, page 81, accessed 19 November 2025.",
  "Australian Computer Society (ACS), Digital Tasmania Strategy 2026-2031, ACS, 2024, page 7, accessed 6 January 2026.",
  "Australian Computer Society (ACS), Digital Tasmania Strategy 2026-2031, ACS, 2024, page 12, accessed 6 January 2026.",
  "Department of Defence, 2024 National Defence Strategy and 2024 Integrated Investment Program, Department of Defence, Australian Government, 2024, page 7, accessed 19 November 2025.",
  "Department of Defence, 2024 National Defence Strategy, Department of Defence, Australian Government, 2024, accessed 19 November 2025.",
  "Department of Defence, 2024 National Defence Strategy, Department of Defence, Australian Government, 2024, accessed 19 November 2025.",
  "Department of Defence, 2024 Integrated Investment Program, Department of Defence, Australian Government, 2024, accessed 19 November 2025.",
  "Department of Defence, Albanese Government to invest up to $7 billion in counter drone defence [media release], Department of Defence, Australian Government, 21 April 2026, accessed 28 April 2026.",
  "S Baker, 'The drone war is moving too fast for old-school defence tech development', CEO Wars, Business Insider, 18 November 2025, accessed 5 January 2026; O Molloy, Drones in Modern Warfare: Lessons Learnt from the War in Ukraine, Australian Army Occasional Paper No. 29, 2024, accessed 6 January 2026.",
  "S Baker, 'The drone war is moving too fast for old-school defence tech development', CEO Wars, Business Insider, 18 November 2025, accessed 5 January 2026.",
  "Department of Defence, Growing sovereign nuclear base will 800 drones delivered to Defence [media release], Department of Defence, Australian Government, 19 August 2025.",
];

export default function PublicSafetyDefenceEmergingTechnologyView({ slug, report }: { slug: string; report: PublicSafetyReport }) {
  return <PublicSafetyPageShell slug={slug} report={report} currentPage="defence_emerging_technology" navigation={{ back:{label:"Defence Workforce Insights",href:`/reports/${slug}/defence_workforce_insights`}, backSecondary:{label:"Executive Summary",href:`/reports/${slug}/executive_summary`}, prev:{label:"Workforce Insights",href:`/reports/${slug}/defence_workforce_insights`}, next:{label:"2. Transitioning Veterans",href:`/reports/${slug}/defence_transitioning_veterans`}, prevPrefix:"Previous Section:", nextPrefix:"Next Section:" }}>
    <section className="rounded-2xl border border-[#E9EAEB] bg-white px-6 py-6"><span className="inline-flex rounded-full bg-[#D7A31A] px-4 py-1.5 text-[10px] font-bold text-white">Theme 1. Emerging Technology · Insight One</span><h1 className="mt-5 text-[40px] font-bold leading-[48px] text-[#252D02]">Emerging Technology</h1><p className="mt-3 text-xs text-[#535862]">Each section below can also be opened individually.</p></section>

    <section className="rounded-2xl border border-[#E9EAEB] bg-white p-6">
      <div className="grid min-h-[170px] overflow-hidden rounded-xl border border-[#E2E4DB] bg-[#FAFAF0]" style={{gridTemplateColumns:"8px 58px 1fr"}}><div className="bg-[#91AD45]"/><div className="pt-6 text-center text-[50px] font-light leading-none text-[#E7E8D9]">1</div><div className="px-5 py-6"><p className="text-[10px] font-semibold uppercase text-[#6C8C20]">Industry Insight 1.1</p><p className="mt-5 max-w-[900px] text-sm font-semibold leading-6 text-[#252D02]">Challenges in rapid adoption of emerging technology remains, due to significant security screening requirements for any new technology adoption. Limitations exist for the speed of being able to upskill employees in the use of any new technology.</p><p className="mt-5 text-xs leading-5 text-[#535862]">The complete supporting report content follows below. Use ← Back to Workforce Insights to return to the presentation anchor.</p></div></div>

      <div className="mt-6"><h2 className="border-b border-[#DADDD4] pb-5 text-2xl font-bold text-[#252D02]">Emerging technologies across the labour market</h2><div className="max-w-[970px] pt-6 text-[13px] leading-[21px] text-[#535862]"><p>Across the broader labour market in Australia, emerging technologies are considered to be drivers of long-term productivity growth. Adopting these emerging technologies requires supporting workforces to rapidly train and upskill, changing traditional approaches to training.<sup>16</sup> It is anticipated that across the labour market, Australia will require 1.3 million technology professionals by 2030, equating to 52,000 employees.<sup>17</sup> Recent data indicates that between 2016 and 2021, 75,000 Information and Communication Technology (ICT) students entered the broader technology sector following completion of a university or VET qualification, which equates to only 15,000 ICT professionals annually.<sup>18</sup></p><p className="mt-4">While not Defence-specific, this shortage indicates the need to ensure the Australian Defence Force workforce is not only appropriately skilled to deploy emerging technologies, but that individuals are attracted and retained, noting the competing need for such professionals across the wider labour market.</p><p className="mt-4">The adoption of the 2024 National Defence Strategy has resulted in a change in capability priorities for the ADF, which has now moved “to an integrated, focused force designed to address Australia&apos;s most significant strategic risks”. This is markedly different from the previous balanced force approach, which was structured to respond to a range of possibilities.<sup>19</sup> Noting this change, ADF stakeholders who were consulted, emphasised the importance of training for capability that is agile and resilient to strategic shocks, and adaptable to government priorities.</p></div></div>
    </section>

    <section className="rounded-2xl border border-[#E9EAEB] bg-white p-6"><h2 className="text-2xl font-bold text-[#252D02]">Sources</h2><ol className="mt-6 space-y-4">{sources.map((source,index)=><li key={source} className="grid grid-cols-[24px_1fr] gap-3 text-xs leading-5 text-[#535862]"><span className="grid size-5 place-items-center rounded-full bg-[#78A800] text-[10px] font-bold text-white">{index+16}</span><span>{source}</span></li>)}</ol></section>
  </PublicSafetyPageShell>;
}
