import { BadgeCheck, Building2, FlaskConical, GraduationCap, Network, ShieldCheck, UserRound } from "lucide-react";
import PublicSafetyPageShell, { type PublicSafetyReport } from "./PublicSafetyPageShell";

const stakeholders = ["ANZPAA", "National Institute of Forensic Science (NIFS)", "State/Territory Police organisations and Australian Federal Police", "Forensic Services South Australia", "ACT Government Analytical Laboratory", "Canberra Institute of Technology"];

export default function PublicSafetyPoliceWorkforceStrategiesView({ slug, report }: { slug: string; report: PublicSafetyReport }) {
  return <PublicSafetyPageShell slug={slug} report={report} currentPage="police_workforce_strategies" navigation={{
    back: { label: "Executive Summary", href: `/reports/${slug}/executive_summary` },
    backSecondary: { label: "Police chapter", href: `/reports/${slug}/police` },
    prev: { label: "Workforce Insights", href: `/reports/${slug}/police_workforce_insights` },
    next: { label: "2025 Strategy Updates", href: `/reports/${slug}/police_update_2025_strategies` },
    prevPrefix: "Previous Section:", nextPrefix: "Next Section:",
  }}>
    <section className="relative min-h-[210px] overflow-hidden rounded-xl border border-[#E9EAEB] bg-white px-7 py-8 lg:pr-[390px]"><span className="inline-flex rounded-full bg-[#1685A6] px-4 py-1.5 text-[10px] font-bold uppercase text-white">POL · Industry-Sector Analysis</span><h1 className="mt-5 text-[42px] font-bold leading-[50px] text-[#252D02]">Proposed Strategy 2026</h1><p className="mt-4 text-sm leading-6 text-[#535862]">Public Skills Australia proposes the following strategies to aligned to the workforce insights identified to support the Police industry-sector:</p><div className="absolute right-8 top-5 hidden h-[170px] w-[330px] lg:block"><span className="absolute left-0 top-16 grid size-12 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><GraduationCap size={24}/></span><span className="absolute left-16 top-2 grid size-14 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><ShieldCheck size={26}/></span><span className="absolute left-[126px] top-0 grid size-28 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><Building2 size={43}/></span><span className="absolute left-[150px] top-[95px] grid size-14 place-items-center rounded-full bg-white text-[#719926]"><Network size={25}/></span><span className="absolute right-8 top-14 grid size-14 place-items-center rounded-full bg-white text-[#719926]"><FlaskConical size={25}/></span><span className="absolute right-0 top-4 grid size-12 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><UserRound size={23}/></span></div></section>

    <section className="overflow-hidden rounded-xl border border-[#E9EAEB] border-t-[10px] border-t-[#1685A6] bg-white p-7"><span className="inline-flex rounded-full bg-[#1685A6] px-4 py-1.5 text-[10px] font-bold uppercase text-white">Strategy 1</span><h2 className="mt-7 text-2xl font-bold text-[#252D02]">Develop Training Products for Digital Forensics</h2><p className="mt-3 border-b border-[#DDE0D9] pb-7 text-sm text-[#535862]">Workforce Insight: Digital Forensics · JSC Function: Training Product Development</p>
      <div className="mt-7 grid gap-10 lg:grid-cols-[1.35fr_1fr]"><div className="space-y-6 text-sm leading-6 text-[#535862]"><div><h3 className="font-bold text-[#252D02]">Workforce Insight:</h3><p>Digital Forensics</p></div><div><h3 className="font-bold text-[#252D02]">JSC Function:</h3><p>Training Product Development</p></div><div><h3 className="font-bold text-[#252D02]">Objective:</h3><p>Develop a digital forensics qualification to be included in the POL Police Training Package.</p></div><div><h3 className="font-bold text-[#252D02]">Approach:</h3><p>This strategy will engage the Australia New Zealand Policing Advisory Agency (ANZPAA) and the National Institute of Forensic Science to develop a digital forensics qualification.</p><p>The approach will be to work through ANZPAA to engage subject matter experts through specialist advisory groups.</p></div><div><h3 className="font-bold text-[#252D02]">Deliverable:</h3><p className="flex items-center gap-2"><BadgeCheck size={16} className="text-[#719926]"/> Accredited Training Products</p></div><div><h3 className="font-bold text-[#252D02]">Impact:</h3><p>Develop nationally consistent approach to training digital forensics for policing and support addressing an area of skills shortage.</p></div><div><h3 className="font-bold text-[#252D02]">Anticipated timing:</h3><p>18-month project</p></div></div>
        <aside><h3 className="text-sm font-bold text-[#252D02]">Key Stakeholders:</h3><div className="mt-4 flex flex-wrap gap-3">{stakeholders.map((stakeholder) => <span key={stakeholder} className="inline-flex rounded-full bg-[#E8F2F6] px-4 py-2 text-xs font-semibold text-[#1685A6]">• &nbsp;{stakeholder}</span>)}</div></aside>
      </div>
    </section>
  </PublicSafetyPageShell>;
}
