"use client";

import { BarChart3, BrainCircuit, Cog, Lightbulb, Search, Users } from "lucide-react";
import PublicSafetyPageShell, { type PublicSafetyReport } from "./PublicSafetyPageShell";

const sources = [
  "Australian Institute for Disaster Resilience (AIDR), Major Incidents Report 2024–25, Australian Government Department of Home Affairs, 2025.",
  "Australian Institute for Disaster Resilience (AIDR), Major Incidents Report 2022–23; Australian Government Department of Home Affairs, 2023; AIDR, Major Incidents Report 2023–24, 2024; AIDR, Major Incidents Report 2024–25, 2025.",
  "M Biskin, Royal Commission into National Natural Disaster Arrangements (Report), Australian Government, 2020, page 453.",
  "Transparency Portal, National Recovery and Resilience Organisation Annual Report 2021–22, Australian Government, 2022.",
  "Australian Institute for Disaster Resilience, Australian Institute for Disaster Resilience Handbook Collection: Community Recovery, 2018, pages 6–7.",
  "Training.gov.au, Training package – PUA Public Safety, Australian Government, 2025.",
  "National Centre for Vocational Education Research (NCVER), Total VET students and courses, 2025.",
  "Australian Institute for Disaster Resilience, National Principles for Disaster Recovery, National Emergency Management Agency, 2018.",
  "Prescribed Burning Centre of Excellence, National Position on Prescribed Burning, Australasian Fire and Emergency Service Authorities Council, 2021.",
  "PUAFIR201 Assist with prescribed burning; PUAFIR402 Conduct simple prescribed burns; PUAFIR406 Develop simple prescribed burn plans; PUAFIR506 Conduct complex prescribed burns; PUAFIR515 Develop complex prescribed burn plans.",
];

function IconCluster() {
  return <div className="absolute right-8 top-5 hidden h-[150px] w-[330px] lg:block"><span className="absolute left-2 top-16 grid size-14 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><Lightbulb size={26}/></span><span className="absolute left-16 top-5 grid size-12 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><Users size={21}/></span><span className="absolute left-[125px] top-0 grid size-20 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><Search size={35}/></span><span className="absolute left-[195px] top-[78px] grid size-14 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><Cog size={26}/></span><span className="absolute right-0 top-12 grid size-16 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><BarChart3 size={31}/></span><span className="absolute right-7 top-0 grid size-12 place-items-center rounded-full bg-[#F2F5E9] text-[#719926]"><BrainCircuit size={22}/></span></div>;
}

export default function PublicSafetyFesDisasterRecoveryThreeView({ slug, report }: { slug: string; report: PublicSafetyReport }) {
  return <PublicSafetyPageShell slug={slug} report={report} currentPage="fes_disaster_recovery" navigation={{ back:{label:"Workforce Insights",href:`/reports/${slug}/fes_workforce_insights`}, backSecondary:{label:"Executive Summary",href:`/reports/${slug}/executive_summary`}, prev:{label:"Workforce Insights",href:`/reports/${slug}/fes_workforce_insights`}, next:{label:"2. Surf Life Saving First Aid",href:`/reports/${slug}/fes_surf_life_saving_first_aid`}, prevPrefix:"Previous Section:", nextPrefix:"Next Section:" }}>
    <section className="relative min-h-[190px] overflow-hidden rounded-2xl border border-[#E9EAEB] bg-white px-6 py-7 lg:px-8"><div className="relative z-10 max-w-[920px]"><span className="inline-flex rounded-full bg-[#D95222] px-4 py-1.5 text-[10px] font-bold text-white">Theme One. Disaster Recovery. Insight One</span><h1 className="mt-5 text-[38px] font-bold leading-[46px] text-[#252D02]">3. Disaster Recovery. Insight Three.</h1><p className="mt-4 max-w-[980px] text-xs leading-5 text-[#535862]">Australia is experiencing a critical challenge in maintaining capability to use fire effectively in the landscape, particularly for complex prescribed burning and backburning during bushfire suppression.</p></div><IconCluster/></section>

    <section className="rounded-xl border border-[#E9EAEB] bg-white p-6 lg:p-8"><h2 className="border-b border-[#E9EAEB] pb-5 text-2xl font-bold text-[#252D02]">Community recovery and prescribed burning</h2><div className="mt-7 space-y-5 text-xs leading-5 text-[#535862]"><p>As described in the National Principles for Disaster Recovery, community involvement in disaster recovery activities is critical for ensuring long-term disaster recovery success and community resilience. Consequently, access to relevant and contemporary disaster recovery training is required to enable community, local government, and state, territory and federal government personnel and volunteers to adequately support communities in times of disaster.</p><p>Connected to this is the role of prescribed burning in decreasing the scale of recovery efforts required after a major fire. Prescribed burning reduces fuel hazards and can assist the success of suppression activities and reduce the intensity, extent and impact of subsequent bushfires. At the same time, insights gained during disaster recovery, such as patterns of fire behaviour, infrastructure vulnerability and ecological impacts can directly inform the planning and prioritisation of prescribed burns.</p><p>However, capability in the use of prescribed burning is declining. Changes in rural and land use, primary industries and forest management, together with shifting policies for fire, land management, emergency services and the environment at different levels of government have contributed to the challenges of maintaining skills.</p></div><div className="mt-7 rounded-lg border border-[#F0D9D1] border-l-[8px] border-l-[#D95222] bg-[#FBECE7] px-6 py-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-white text-[#719926]"><Users size={20}/></span><strong className="text-sm text-[#252D02]">Industry Insight</strong></div><p className="mt-4 text-xs leading-5 text-[#535862]">Challenges in access to nationally accredited disaster recovery training products leads to inconsistencies in recovery outcomes, reduced community trust and limits the ability of communities to rebuild from the impacts of disasters.</p></div><p className="mt-6 text-xs leading-5 text-[#535862]">The Australasian Fire and Emergency Services Authorities Council (AFAC) in conjunction with the Forest Fire Management Group developed a series of documents including principles, frameworks and guidelines as part of the National Burning Project. These documents are aimed at developing nationally consistent approaches to the use of prescribed burning by the Fire and Emergency Services industry-sector. This prescribed burning capability is supported by five units of competency in the PUA Public Safety Training Package.</p></section>

    <section className="rounded-xl border border-[#E9EAEB] bg-white p-6 lg:p-8"><h2 className="text-xl font-bold text-[#252D02]">Sources</h2><ul className="mt-5 space-y-3">{sources.map((source,index)=><li key={source} className="flex gap-3 text-[11px] leading-5 text-[#535862]"><span className="mt-1 grid size-4 shrink-0 place-items-center rounded-full bg-[#7F9C37] text-[8px] text-white">{53+index}</span><span>{source}</span></li>)}</ul></section>
  </PublicSafetyPageShell>;
}
