"use client";

import { ArrowLeft, ArrowRight, BookOpen, BriefcaseBusiness, ClipboardList, Landmark, Network, ShieldCheck } from "lucide-react";
import { useState } from "react";
import PublicSafetyPageShell, { type PublicSafetyReport } from "./PublicSafetyPageShell";

const strategies = [
  { number:"01", owner:"Department of Defence", period:"2023–ongoing", title:"Australian Government National Defence: Defence Strategic Review", heading:"01 · National Defence: Defence Strategic Review", summary:"The National Defence: Defence Strategic Review 2023 outlined recommended reforms to Defence’s posture and structure. The review provides 62 recommendations across a range of strategic focus areas, including but not limited to workforce, capability, technology, resourcing and logistics. This strategic review preceded the development of the 2024 National Defence Strategy and update of the Integrated Investment Program 2024. It recommended a biennial strategic update through a National Defence Strategy, with the 2024 National Defence Strategy the first iteration of the strategic update. The Defence Strategic Review notes that it should be considered in conjunction with the 2024 National Defence Strategy and the Integrated Investment Program 2024.\n\nInitial progress on a range of other recommendation focus areas is described at the Australian Government Transparency Portal.41 Continued progress against the recommendations is also documented in the Defence Annual Report 2024–25.42", consultation:"Considered in conjunction with the National Defence Strategy 2024 and the Integrated Investment Plan 2024, which provided detail and context for engagements and consultations.", update2025:"Informed the development of Workforce Strategies identified in the National Defence Strategy 2024 and the Integrated Investment Program 2024. Together they provide the framework for Public Skills Australia’s Defence projects.", update2026:"Will provide context and data for the development of initial research for the Support Defence skill and capability requirements to operationalise drones project." },
  { number:"02", owner:"Department of Defence", period:"2024", title:"Australian Government National Defence Strategy 2024", heading:"02 · Australian Government National Defence Strategy 2024", summary:"The 2024 National Defence Strategy sets the strategic direction for Australia’s defence policy, planning, capabilities and workforce priorities.", consultation:"Provides the central strategic context for Defence industry-sector engagement and consultation.", update2025:"Informed workforce strategies and priority capability areas identified across Defence projects.", update2026:"Will continue to guide training product development and workforce capability priorities." },
  { number:"03", owner:"Department of Defence", period:"2024", title:"Australian Government 2024 Defence Workforce Plan", heading:"03 · Australian Government 2024 Defence Workforce Plan", summary:"The Defence Workforce Plan outlines workforce growth, attraction, development and retention priorities needed to deliver Defence capability.", consultation:"Provides workforce planning context for engagement with Defence and education stakeholders.", update2025:"Informed youth development, emerging technology and workforce pathways projects.", update2026:"Will support projects aimed at a skilled, adaptable and inclusive Defence workforce." },
  { number:"04", owner:"Department of Defence", period:"Ongoing", title:"Australian Government Defence Industry Development Strategy", heading:"04 · Defence Industry Development Strategy", summary:"The Defence Industry Development Strategy establishes priorities for sovereign defence industrial capability and a resilient industry workforce.", consultation:"Supports consultation with industry, government and training system stakeholders.", update2025:"Informed analysis of Defence industry capability and workforce requirements.", update2026:"Will guide alignment between VET products and priority industry capabilities." },
  { number:"05", owner:"Department of Defence", period:"2024", title:"Australian Government Integrated Investment Program", heading:"05 · Integrated Investment Program", summary:"The Integrated Investment Program describes capability investment priorities and the resources required to implement the National Defence Strategy.", consultation:"Provides capability and investment context for workforce consultations.", update2025:"Informed emerging technology workforce strategies and research.", update2026:"Will inform Defence micro-credentials and drone capability work." },
  { number:"06", owner:"Australian Government", period:"2024", title:"Australian Government Response to the Final Report of the Royal Commission into Defence and Veteran Suicide", heading:"06 · Government Response to the Royal Commission", summary:"The Australian Government response sets out actions addressing the recommendations of the Royal Commission into Defence and Veteran Suicide.", consultation:"Provides context for engagement on veteran transition and recognition of Defence skills.", update2025:"Informed scoping of pathways for transitioning veterans.", update2026:"Will guide work supporting Recommendation 83 and civilian recognition of Defence experience." },
  { number:"07", owner:"Department of Defence", period:"2024", title:"2024 Naval Shipbuilding and Sustainment Plan", heading:"07 · Naval Shipbuilding and Sustainment Plan", summary:"The plan outlines Australia’s long-term naval shipbuilding and sustainment priorities and associated workforce needs.", consultation:"Provides context for maritime workforce and training consultations.", update2025:"Informed analysis of priority Defence occupations and capabilities.", update2026:"Will support alignment of workforce development with sovereign maritime capability." },
  { number:"08", owner:"Department of Defence", period:"2025", title:"Defence Digital Strategy and Roadmap 2025", heading:"08 · Defence Digital Strategy and Roadmap 2025", summary:"The Defence Digital Strategy and Roadmap establishes priorities for digital transformation, data, cyber capability and technology adoption.", consultation:"Provides context for engagement on cyber, AI and emerging technology skills.", update2025:"Informed the Defence Cyber and Space Skill Set projects.", update2026:"Will guide future-ready training products and emerging technology workforce strategies." },
];

export default function PublicSafetyDefenceExistingStrategiesView({ slug, report }: { slug: string; report: PublicSafetyReport }) {
  const [active, setActive] = useState(0);
  const strategy = strategies[active];
  return <PublicSafetyPageShell slug={slug} report={report} currentPage="defence_existing_strategies" navigation={{back:{label:"Executive Summary",href:`/reports/${slug}/executive_summary`},backSecondary:{label:"Defence chapter",href:`/reports/${slug}/defence`},prev:{label:"2025 Strategy Updates",href:`/reports/${slug}/defence_update_2025_strategies`},next:{label:"Defence Veterans’ Programs and Initiatives",href:`/reports/${slug}/defence_federal_initiatives`},prevPrefix:"Previous Section:",nextPrefix:"Next Section:"}}>
    <section className="relative min-h-[190px] overflow-hidden rounded-2xl border border-[#E9EAEB] bg-white px-6 py-8 lg:px-8"><div className="relative z-10"><span className="inline-flex rounded-full bg-[#D7A31A] px-4 py-1.5 text-[10px] font-bold text-white">DEFENCE</span><h1 className="mt-5 text-[40px] font-bold leading-[48px] text-[#252D02]">Existing Industry-Sector Strategies</h1><p className="mt-4 text-sm text-[#535862]">Select a strategy to open more detail on how it informs Public Skills Australia’s work.</p></div><div className="absolute right-12 top-8 hidden h-[130px] w-[350px] items-center justify-between lg:flex">{[Network,ShieldCheck,ClipboardList,Landmark,BriefcaseBusiness,BookOpen].map((Icon,index)=><span key={index} className={`grid place-items-center rounded-full bg-[#F2F5E7] text-[#719926] ${index===3?"size-20":"size-12"}`}><Icon size={index===3?34:21} strokeWidth={1.5}/></span>)}</div></section>
    <section><h2 className="mb-3 text-lg font-bold">STRATEGIES · 8 · SELECT TO OPEN</h2><div className="grid items-start gap-6 lg:grid-cols-[360px_1fr]"><div className="space-y-3">{strategies.map((item,index)=><button key={item.number} type="button" onClick={()=>setActive(index)} className={`grid min-h-[100px] w-full grid-cols-[1fr_42px] items-center gap-3 rounded-xl border bg-white px-5 py-4 text-left ${active===index?"border-[#D6A21D] ring-1 ring-[#D6A21D]":"border-[#E1E3DC]"}`}><span><span className="block text-[10px] font-semibold uppercase text-[#C5951B]">{item.number} · {item.owner}</span><strong className="mt-4 block text-[14px] leading-5 text-[#252D02]">{item.title}</strong></span><span className={`grid size-9 place-items-center rounded-full ${active===index?"border border-[#A9BE67] bg-white":"bg-[#7BC900]"}`}><ArrowRight size={15}/></span></button>)}</div>
      <article className="rounded-xl bg-[#ECEDE2] p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-[#D7A31A] px-5 py-2 text-xs font-bold text-white">{strategy.number} · {strategy.period}</span><div className="flex gap-3">{active>0&&<button type="button" onClick={()=>setActive(active-1)} className="inline-flex h-10 items-center gap-2 rounded-full border border-[#A9BE67] bg-white px-5 text-xs font-semibold text-[#68821E]"><ArrowLeft size={15}/> Previous</button>}<button type="button" onClick={()=>setActive((active+1)%strategies.length)} className="inline-flex h-10 items-center gap-2 rounded-full bg-[#7BC900] px-5 text-xs font-semibold">Next <ArrowRight size={15}/></button></div></div><div className="mt-6 rounded-xl bg-white p-6"><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-bold">{strategy.heading}</h3><span className="shrink-0 rounded-full bg-[#ECEDE7] px-5 py-2 text-[10px] uppercase text-[#686D68]">{strategy.owner} · {strategy.period}</span></div><h4 className="mt-7 text-xs font-bold uppercase text-[#6C8C20]">Summary</h4><div className="mt-4 whitespace-pre-line text-[13px] leading-[21px] text-[#535862]">{strategy.summary}</div><div className="mt-6 border-t border-[#DADDD4] pt-6"><p className="mb-4 text-xs font-semibold text-[#6C8C20]">How this informs Public Skills Australia’s work</p>{[["Consultation and engagement:",strategy.consultation],["2025 Workforce Strategies",strategy.update2025],["2026 Workforce Strategies",strategy.update2026]].map(([title,body])=><div key={title} className="mb-4 rounded-xl border-l-[8px] border-[#D7A31A] bg-[#FBF4E8] p-6 text-[13px] leading-[21px] text-[#535862]"><h4 className="mb-3 text-base font-semibold text-[#252D02]">{title}</h4><p>{body}</p></div>)}</div></div></article></div></section>
    <section className="rounded-2xl border border-[#E9EAEB] bg-white p-6"><h2 className="text-2xl font-bold">Sources</h2><ol className="mt-6 space-y-3 text-xs leading-5 text-[#535862]">{["Australian Government, ‘Progress on the Defence Strategic Review’, Transparency Portal, Australian Government website, 2026, accessed 3 February 2026.","Department of Defence, Defence Annual Report 2024–25, Department of Defence, Australian Government, 2025, accessed 4 February 2026."].map((source,index)=><li key={source} className="grid grid-cols-[24px_1fr] gap-3"><span className="grid size-5 place-items-center rounded-full bg-[#78A800] text-[10px] font-bold text-white">{index+41}</span><span>{source}</span></li>)}</ol></section>
  </PublicSafetyPageShell>;
}
